"""
Tiles views.

A tiles view previews how a collection of images would look when split into
fixed-size tiles: each tile is one sample of the view, carrying only the
labels that touch it. It is a view, not a data transformation: the source
collection is only read, and nothing done in the view is written back to it.

| Copyright 2017-2026, Voxel51, Inc.
| `voxel51.com <https://voxel51.com/>`_
|
"""

import math

import eta.core.utils as etau

import fiftyone.core.dataset as fod
import fiftyone.core.expressions as foe
import fiftyone.core.fields as fof
import fiftyone.core.labels as fol
import fiftyone.core.media as fom
import fiftyone.core.patches as fop
import fiftyone.core.validation as fova

F = foe.ViewField

# Also hardcoded in app/packages/looker/src/zoom.ts; tiles_tests.py checks
# that the two agree
TILE_FIELD = "tile_regions"

# Tolerance for comparing normalized coordinates
_EPS = 1e-9

# Whether a tile fully contains a label; ordered so that a label's status is
# the max of its statuses in each dimension
_FITS = 0
_CROSSES = 1
_TOO_LARGE = 2

# Label types whose labels are filtered to those that touch each tile
_LIST_TYPES = (fol.Detections, fol.Polylines, fol.Keypoints)
_SINGLE_TYPES = (fol.Detection, fol.Polyline, fol.Keypoint)


class TilesView(fop.PatchesView):
    """A :class:`fiftyone.core.patches.PatchesView` of the tiles of a
    collection's images, as generated by
    :class:`fiftyone.core.stages.ToTiles`.

    Unlike other patches views, a tiles view never writes to its source
    collection: tags and label edits made in the view stay in the view.

    Its labels are in coordinates of the full images. Use
    :meth:`materialize` or :meth:`export` to turn its tiles into images whose
    labels are clipped to the tiles.
    """

    __slots__ = ()

    @property
    def _label_fields(self):
        return []

    def materialize(self, output_dir, **kwargs):
        """Creates a dataset that contains the tiles of this view as images,
        whose labels are clipped to the tiles and re-normalized to them.

        See :meth:`fiftyone.utils.tiles.materialize_tiles` for details.

        Examples::

            import fiftyone as fo
            import fiftyone.zoo as foz

            dataset = foz.load_zoo_dataset("quickstart")
            dataset.compute_metadata()

            tiles = dataset.to_tiles(tile_size=(256, 256), overlap=32)
            tiles_dataset = tiles.materialize("/tmp/quickstart-tiles")

        Args:
            output_dir: the directory in which to write the tile images
            **kwargs: optional keyword arguments for
                :meth:`fiftyone.utils.tiles.materialize_tiles`

        Returns:
            a :class:`fiftyone.core.dataset.Dataset`
        """
        import fiftyone.utils.tiles as fout

        return fout.materialize_tiles(self, output_dir, **kwargs)

    def export(self, *args, **kwargs):
        """Exports the tiles of this view as images, whose labels are clipped
        to the tiles and re-normalized to them, in any format.

        Takes the same arguments as
        :meth:`fiftyone.core.collections.SampleCollection.export`, except
        that ``export_media`` can only be ``True`` or ``"move"``, plus
        ``empty_tiles``, which decides whether tiles without labels are
        exported with empty labels (``"keep"``), without labels
        (``"keep_without_labels"``), or not at all (``"skip"``), and
        ``join_polygon_parts``. See
        :meth:`fiftyone.utils.tiles.export_tiles` for details.

        Examples::

            import fiftyone as fo
            import fiftyone.zoo as foz

            dataset = foz.load_zoo_dataset("quickstart")
            dataset.compute_metadata()

            tiles = dataset.to_tiles(tile_size=(256, 256), overlap=32)
            tiles.export(
                export_dir="/tmp/quickstart-yolo",
                dataset_type=fo.types.YOLOv5Dataset,
                label_field="ground_truth",
                empty_tiles="skip",
            )
        """
        import fiftyone.utils.tiles as fout

        return fout.export_tiles(self, *args, **kwargs)


def compute_tiles(img_w, img_h, tile_size, overlap=0):
    """Computes the tiles that cover an image.

    Tiles are laid out on a regular grid with the given overlap, using the
    minimum number of rows and columns that cover the image. The last tile of
    each row/column is shifted back so that it ends exactly at the image
    edge, which may increase its overlap with the previous tile. In any
    dimension in which the image is smaller than the tile, the tiles are
    clamped to the image size instead.

    Args:
        img_w: the image width, in pixels
        img_h: the image height, in pixels
        tile_size: a ``(width, height)`` tuple specifying the tile size in
            pixels
        overlap (0): the overlap between adjacent tiles. Values >= 1 are
            interpreted as pixels; values in [0, 1) are interpreted as
            fractions of the tile size

    Returns:
        a list of dicts with ``row``, ``col``, ``x``, ``y``, ``width``, and
        ``height`` keys, in pixels, in row-major order
    """
    tile_w, tile_h, overlap_x, overlap_y = _parse_tiling(tile_size, overlap)

    if img_w <= 0 or img_h <= 0:
        raise ValueError(
            "Image dimensions must be positive, got (%s x %s)" % (img_w, img_h)
        )

    xs = _tile_starts(img_w, tile_w, tile_w - overlap_x)
    ys = _tile_starts(img_h, tile_h, tile_h - overlap_y)
    width = min(tile_w, img_w)
    height = min(tile_h, img_h)

    return [
        {"row": r, "col": c, "x": x, "y": y, "width": width, "height": height}
        for r, y in enumerate(ys)
        for c, x in enumerate(xs)
    ]


def compute_tile_detections(img_w, img_h, tile_size, overlap=0):
    """Computes the tiles that cover an image as
    :class:`fiftyone.core.labels.Detection` instances.

    See :meth:`compute_tiles` for how tiles are laid out.

    Args:
        img_w: the image width, in pixels
        img_h: the image height, in pixels
        tile_size: a ``(width, height)`` tuple specifying the tile size in
            pixels
        overlap (0): the overlap between adjacent tiles. Values >= 1 are
            interpreted as pixels; values in [0, 1) are interpreted as
            fractions of the tile size

    Returns:
        a list of :class:`fiftyone.core.labels.Detection` instances whose
        labels are ``tile_<row>_<col>``
    """
    return [
        fol.Detection(
            label="tile_%d_%d" % (t["row"], t["col"]),
            bounding_box=[
                t["x"] / img_w,
                t["y"] / img_h,
                t["width"] / img_w,
                t["height"] / img_h,
            ],
        )
        for t in compute_tiles(img_w, img_h, tile_size, overlap=overlap)
    ]


def make_tiles_dataset(
    sample_collection,
    tile_size,
    overlap=0,
    other_fields=None,
    min_label_coverage=0.0,
    include_indexes=False,
    name=None,
    persistent=False,
    _generated=False,
):
    """Creates a dataset that contains one sample per tile of each image in
    the collection.

    See :meth:`compute_tiles` for how tiles are laid out. Each tile's region
    is stored as a :class:`fiftyone.core.labels.Detection` in a
    ``tile_regions`` field, and a ``sample_id`` field records the sample ID
    from which each tile was taken.

    Top-level :class:`fiftyone.core.labels.Detections`,
    :class:`fiftyone.core.labels.Polylines`, and
    :class:`fiftyone.core.labels.Keypoints` fields (and their single-label
    variants) included via ``other_fields`` only keep the labels that touch
    each tile. Labels keep their full-image coordinates. Other fields are
    copied as-is.

    The tiles are computed in the database: the source collection is only
    read, never written.

    Args:
        sample_collection: a
            :class:`fiftyone.core.collections.SampleCollection` of images,
            whose samples must have their
            :class:`fiftyone.core.metadata.ImageMetadata` populated
        tile_size: a ``(width, height)`` tuple specifying the tile size in
            pixels
        overlap (0): the overlap between adjacent tiles. Values >= 1 are
            interpreted as pixels; values in [0, 1) are interpreted as
            fractions of the tile size
        other_fields (None): controls whether fields other than the tile
            regions and the default sample fields are included. Can be any
            of the following:

            -   a field or list of fields to include
            -   ``True`` to include all other fields
            -   ``None``/``False`` to include no other fields
        min_label_coverage (0.0): the minimum fraction of a label's area that
            must lie within a tile for the tile to keep it. By default, every
            label that touches a tile is kept. The area of polylines and
            keypoints is that of their bounding box
        include_indexes (False): whether to recreate any custom indexes on
            ``other_fields`` on the new dataset (True) or a list of specific
            indexes or index prefixes to recreate. By default, no custom
            indexes are recreated
        name (None): a name for the dataset
        persistent (False): whether the dataset should persist in the
            database after the session terminates

    Returns:
        a :class:`fiftyone.core.dataset.Dataset`
    """
    fova.validate_collection(sample_collection, media_type=fom.IMAGE)

    if sample_collection._is_frames:
        raise ValueError("Tiles views of frames are not supported")

    tile_w, tile_h, overlap_x, overlap_y = _parse_tiling(tile_size, overlap)

    if not 0 <= min_label_coverage <= 1:
        raise ValueError(
            "min_label_coverage must be in [0, 1], got %s" % min_label_coverage
        )

    _validate_metadata(sample_collection)

    other_fields = _parse_other_fields(sample_collection, other_fields)

    dataset = fod.Dataset(
        name=name, persistent=persistent, _patches=_generated
    )
    dataset.media_type = fom.IMAGE
    dataset.add_sample_field("sample_id", fof.ObjectIdField)
    dataset.create_index("sample_id")
    dataset.add_sample_field(
        TILE_FIELD, fof.EmbeddedDocumentField, embedded_doc_type=fol.Detection
    )

    if other_fields:
        src_schema = sample_collection.get_field_schema()
        add_schema = {f: src_schema[f] for f in other_fields}
        dataset._sample_doc_cls.merge_field_schema(add_schema)

    fod._clone_indexes_for_patches_view(
        sample_collection,
        dataset,
        other_fields=other_fields,
        include_indexes=include_indexes,
    )

    fop._make_pretty_summary(dataset)

    label_fields = _get_filterable_label_fields(
        sample_collection, other_fields or []
    )
    pipeline = _make_tiles_pipeline(
        tile_w,
        tile_h,
        tile_w - overlap_x,
        tile_h - overlap_y,
        other_fields or [],
        label_fields,
        min_label_coverage,
    )
    fop._write_samples(dataset, sample_collection.mongo(pipeline))

    # $out gave each tile a new ID; like other patches views, a tile's region
    # label shares the ID of its sample
    dataset._sample_collection.update_many(
        {}, [{"$set": {TILE_FIELD + "._id": "$_id"}}]
    )

    return dataset


def count_uncontained_labels(
    sample_collection, tile_size, overlap=0, fields=None
):
    """Counts the labels that no tile of their image would fully contain.

    See :meth:`compute_tiles` for how tiles are laid out. A label that no
    tile fully contains is either larger than a tile in at least one
    dimension, which only larger tiles can fix, or crosses the borders
    between tiles, which more overlap can fix: a label that is no larger
    than the overlap always fits in a tile.

    Only the part of a label that lies inside its image is considered. The
    box of a polyline or keypoint is the bounding box of its points.

    Args:
        sample_collection: a
            :class:`fiftyone.core.collections.SampleCollection` of images,
            whose samples must have their
            :class:`fiftyone.core.metadata.ImageMetadata` populated
        tile_size: a ``(width, height)`` tuple specifying the tile size in
            pixels
        overlap (0): the overlap between adjacent tiles. Values >= 1 are
            interpreted as pixels; values in [0, 1) are interpreted as
            fractions of the tile size
        fields (None): a :class:`fiftyone.core.labels.Detection`,
            :class:`fiftyone.core.labels.Detections`,
            :class:`fiftyone.core.labels.Polyline`,
            :class:`fiftyone.core.labels.Polylines`,
            :class:`fiftyone.core.labels.Keypoint`, or
            :class:`fiftyone.core.labels.Keypoints` field or list of such
            fields to count. By default, all top-level fields of these types
            are counted

    Returns:
        a dict mapping each field to a dict with the following keys:

        -   ``count``: the number of labels in the field
        -   ``uncontained``: the number of labels that no tile fully contains
        -   ``too_large``: the number of those labels that are larger than a
            tile in at least one dimension
    """
    fova.validate_collection(sample_collection, media_type=fom.IMAGE)

    if sample_collection._is_frames:
        raise ValueError("Tiles views of frames are not supported")

    tile_w, tile_h, overlap_x, overlap_y = _parse_tiling(tile_size, overlap)

    _validate_metadata(sample_collection)

    label_fields = _parse_label_fields(sample_collection, fields)
    if not label_fields:
        return {}

    pipeline = _make_uncontained_pipeline(
        tile_w, tile_h, tile_w - overlap_x, tile_h - overlap_y, label_fields
    )

    try:
        result = next(iter(sample_collection._aggregate(pipeline=pipeline)))
    except StopIteration:
        result = {}

    counts = {}
    for i, path in enumerate(label_fields):
        key = "f%d" % i
        counts[path] = {
            "count": result.get(key + "_count", 0),
            "uncontained": result.get(key + "_uncontained", 0),
            "too_large": result.get(key + "_too_large", 0),
        }

    return counts


def _parse_tiling(tile_size, overlap):
    try:
        tile_w, tile_h = tile_size
    except (TypeError, ValueError):
        raise ValueError(
            "tile_size must be a (width, height) tuple, got %s" % (tile_size,)
        )

    if tile_w != int(tile_w) or tile_h != int(tile_h):
        raise ValueError("tile_size must be in pixels, got %s" % (tile_size,))

    tile_w, tile_h = int(tile_w), int(tile_h)

    if tile_w <= 0 or tile_h <= 0:
        raise ValueError(
            "Tile dimensions must be positive, got (%d x %d)"
            % (tile_w, tile_h)
        )

    if overlap < 0:
        raise ValueError("Overlap must be >= 0, got %s" % overlap)

    if overlap < 1:
        overlap_x = round(overlap * tile_w)
        overlap_y = round(overlap * tile_h)
    else:
        overlap_x = overlap_y = int(round(overlap))

    if overlap_x >= tile_w or overlap_y >= tile_h:
        raise ValueError(
            "Overlap (%s) must be less than the tile size (%d x %d)"
            % (overlap, tile_w, tile_h)
        )

    return tile_w, tile_h, overlap_x, overlap_y


def _tile_starts(img_len, tile_len, stride):
    if img_len <= tile_len:
        return [0]

    num = math.ceil((img_len - tile_len) / stride) + 1
    return [min(i * stride, img_len - tile_len) for i in range(num)]


def _validate_metadata(sample_collection):
    has_size = (F("metadata.width") > 0) & (F("metadata.height") > 0)
    num_missing = sample_collection.match(~has_size).count()

    if num_missing > 0:
        raise ValueError(
            "Found %d sample(s) without metadata. You must run "
            "`compute_metadata()` before creating a tiles view" % num_missing
        )


def _parse_other_fields(sample_collection, other_fields):
    if other_fields is None or other_fields is False:
        return None

    src_schema = sample_collection.get_field_schema()
    default_fields = set(sample_collection._get_default_sample_fields())

    # Fields that tiles views define themselves
    reserved = {TILE_FIELD, "sample_id"}

    if other_fields is True:
        return [
            f
            for f in src_schema
            if f not in default_fields and f not in reserved
        ]

    if etau.is_str(other_fields):
        other_fields = [other_fields]

    other_fields = list(other_fields)

    conflicts = [f for f in other_fields if f in reserved]
    if conflicts:
        raise ValueError(
            "Field(s) %s cannot be included in a tiles view, which defines "
            "fields with those names" % conflicts
        )

    missing = [f for f in other_fields if f not in src_schema]
    if missing:
        raise ValueError("Collection has no field(s) %s" % missing)

    return [f for f in other_fields if f not in default_fields]


def _get_filterable_label_fields(sample_collection, other_fields):
    label_fields = {}
    for path in other_fields:
        field = sample_collection.get_field(path)
        if not isinstance(field, fof.EmbeddedDocumentField):
            continue

        if issubclass(field.document_type, _LIST_TYPES + _SINGLE_TYPES):
            label_fields[path] = field.document_type

    return label_fields


def _parse_label_fields(sample_collection, fields):
    if fields is None:
        # The label fields that a tiles view would filter
        other_fields = _parse_other_fields(sample_collection, True)
        return _get_filterable_label_fields(sample_collection, other_fields)

    if etau.is_str(fields):
        fields = [fields]

    label_fields = _get_filterable_label_fields(sample_collection, fields)

    unsupported = [f for f in fields if f not in label_fields]
    if unsupported:
        raise ValueError(
            "Field(s) %s are not Detection(s), Polyline(s), or Keypoint(s) "
            "fields" % unsupported
        )

    return label_fields


def _make_tiles_pipeline(
    tile_w,
    tile_h,
    stride_x,
    stride_y,
    other_fields,
    label_fields,
    min_label_coverage,
):
    project = {
        "_id": False,
        "_media_type": True,
        "filepath": True,
        "metadata": True,
        "tags": True,
        "created_at": True,
        "last_modified_at": True,
        "_sample_id": "$_id",
        TILE_FIELD: _tiles_expr(tile_w, tile_h, stride_x, stride_y),
    }
    for f in other_fields:
        project[f] = True

    pipeline = [
        {"$project": project},
        {"$unwind": "$" + TILE_FIELD},
        {"$addFields": {"_rand": {"$rand": {}}}},
    ]

    if label_fields:
        # The tile's normalized [x, y, w, h], for filtering its labels
        tile_box = "$" + TILE_FIELD + ".bounding_box"
        filters = {
            path: _filter_field_expr(path, label_type, min_label_coverage)
            for path, label_type in label_fields.items()
        }
        pipeline.extend(
            [
                {"$addFields": {"_tile_box": tile_box}},
                {"$addFields": filters},
                {"$unset": "_tile_box"},
            ]
        )

    return pipeline


def _num_tiles_expr(img_len, tile_len, stride):
    steps = {
        "$ceil": {"$divide": [{"$subtract": [img_len, tile_len]}, stride]}
    }
    return {
        "$cond": [
            {"$lte": [img_len, tile_len]},
            1,
            {"$add": [{"$toInt": steps}, 1]},
        ]
    }


def _tile_start_expr(index, img_len, tile_len, stride):
    last_start = {"$subtract": [img_len, {"$min": [tile_len, img_len]}]}
    return {"$min": [{"$multiply": [index, stride]}, last_start]}


def _tiles_expr(tile_w, tile_h, stride_x, stride_y):
    """The expression that computes an image's tiles; mirrors
    :meth:`compute_tiles`.
    """
    img_w = "$metadata.width"
    img_h = "$metadata.height"
    x = _tile_start_expr("$$col", img_w, tile_w, stride_x)
    y = _tile_start_expr("$$row", img_h, tile_h, stride_y)
    width = {"$min": [tile_w, img_w]}
    height = {"$min": [tile_h, img_h]}

    tile = {
        "_cls": "Detection",
        "tags": [],
        "label": {
            "$concat": [
                "tile_",
                {"$toString": "$$row"},
                "_",
                {"$toString": "$$col"},
            ]
        },
        "bounding_box": [
            {"$divide": [x, img_w]},
            {"$divide": [y, img_h]},
            {"$divide": [width, img_w]},
            {"$divide": [height, img_h]},
        ],
    }

    cols = {
        "$map": {
            "input": {"$range": [0, _num_tiles_expr(img_w, tile_w, stride_x)]},
            "as": "col",
            "in": tile,
        }
    }
    rows = {
        "$map": {
            "input": {"$range": [0, _num_tiles_expr(img_h, tile_h, stride_y)]},
            "as": "row",
            "in": cols,
        }
    }

    return {
        "$reduce": {
            "input": rows,
            "initialValue": [],
            "in": {"$concatArrays": ["$$value", "$$this"]},
        }
    }


def _filter_field_expr(path, label_type, min_label_coverage):
    field = "$" + path

    if issubclass(label_type, _LIST_TYPES):
        list_field = label_type._LABEL_LIST_FIELD
        single_type = fol._LABEL_LIST_TO_SINGLE_MAP[label_type]
        keep = {
            "$filter": {
                "input": {"$ifNull": [field + "." + list_field, []]},
                "as": "label",
                "cond": _touches_tile_expr(
                    "$$label", single_type, min_label_coverage
                ),
            }
        }
        filtered = {"$mergeObjects": [field, {list_field: keep}]}
    else:
        filtered = {
            "$cond": [
                _touches_tile_expr(field, label_type, min_label_coverage),
                field,
                None,
            ]
        }

    return {"$cond": [{"$eq": [{"$type": field}, "object"]}, filtered, None]}


def _touches_tile_expr(label, label_type, min_label_coverage):
    """The expression that decides whether a tile keeps a label, given the
    tile's normalized ``[x, y, w, h]`` box in ``$_tile_box``.
    """
    return _label_box_expr(
        label, label_type, _box_touches_tile_expr(min_label_coverage), False
    )


def _label_box_expr(label, label_type, in_expr, missing):
    """Evaluates ``in_expr`` with the label's normalized bounding box bound to
    ``$$x, $$y, $$w, $$h``, or returns ``missing`` if the label has no box.

    The box of a polyline or keypoint is the bounding box of its points.
    """
    if issubclass(label_type, fol.Detection):
        box = label + ".bounding_box"
        coords = {
            "x": {"$arrayElemAt": [box, 0]},
            "y": {"$arrayElemAt": [box, 1]},
            "w": {"$arrayElemAt": [box, 2]},
            "h": {"$arrayElemAt": [box, 3]},
        }
        return {
            "$let": {
                "vars": coords,
                "in": {
                    "$cond": [
                        {"$gte": ["$$x", -math.inf]},  # a missing box
                        in_expr,
                        missing,
                    ]
                },
            }
        }

    if issubclass(label_type, fol.Polyline):
        # a list of shapes, each a list of points
        points = {
            "$reduce": {
                "input": {"$ifNull": [label + ".points", []]},
                "initialValue": [],
                "in": {"$concatArrays": ["$$value", "$$this"]},
            }
        }
    else:
        points = {"$ifNull": [label + ".points", []]}

    # Hidden keypoints are stored as NaN, which (like None) fails any
    # comparison with a number
    valid_points = {
        "$filter": {
            "input": points,
            "as": "p",
            "cond": {
                "$and": [
                    {"$gte": [{"$arrayElemAt": ["$$p", 0]}, -math.inf]},
                    {"$gte": [{"$arrayElemAt": ["$$p", 1]}, -math.inf]},
                ]
            },
        }
    }
    xs = {"$map": {"input": "$$pts", "in": {"$arrayElemAt": ["$$this", 0]}}}
    ys = {"$map": {"input": "$$pts", "in": {"$arrayElemAt": ["$$this", 1]}}}

    return {
        "$let": {
            "vars": {"pts": valid_points},
            "in": {
                "$cond": [
                    {"$gt": [{"$size": "$$pts"}, 0]},
                    {
                        "$let": {
                            "vars": {
                                "x": {"$min": xs},
                                "y": {"$min": ys},
                                "w": {
                                    "$subtract": [{"$max": xs}, {"$min": xs}]
                                },
                                "h": {
                                    "$subtract": [{"$max": ys}, {"$min": ys}]
                                },
                            },
                            "in": in_expr,
                        }
                    },
                    missing,
                ]
            },
        }
    }


def _box_touches_tile_expr(min_label_coverage):
    """Decides whether the box ``$$x, $$y, $$w, $$h`` touches the tile.

    A box with area must overlap the tile with positive area, covering at
    least ``min_label_coverage`` of the box. A degenerate box (a point or a
    straight segment) must intersect the tile.
    """
    tx = {"$arrayElemAt": ["$_tile_box", 0]}
    ty = {"$arrayElemAt": ["$_tile_box", 1]}
    tw = {"$arrayElemAt": ["$_tile_box", 2]}
    th = {"$arrayElemAt": ["$_tile_box", 3]}

    x2 = {"$add": ["$$x", "$$w"]}
    y2 = {"$add": ["$$y", "$$h"]}
    tx2 = {"$add": [tx, tw]}
    ty2 = {"$add": [ty, th]}

    inter_w = {"$subtract": [{"$min": [x2, tx2]}, {"$max": ["$$x", tx]}]}
    inter_h = {"$subtract": [{"$min": [y2, ty2]}, {"$max": ["$$y", ty]}]}
    area = {"$multiply": ["$$w", "$$h"]}

    # Normalized coordinates carry float rounding (0.001 + 0.021 > 0.022), so
    # edges are compared with a tolerance far below a pixel, and coverage
    # with a relative one
    overlaps = {
        "$and": [
            {"$gt": [inter_w, _EPS]},
            {"$gt": [inter_h, _EPS]},
            {
                "$gte": [
                    {"$multiply": [inter_w, inter_h]},
                    {
                        "$multiply": [
                            min_label_coverage * (1 - _EPS),
                            area,
                        ]
                    },
                ]
            },
        ]
    }
    intersects = {
        "$and": [
            {"$lte": ["$$x", tx2]},
            {"$gte": [x2, tx]},
            {"$lte": ["$$y", ty2]},
            {"$gte": [y2, ty]},
        ]
    }

    return {"$cond": [{"$gt": [area, 0]}, overlaps, intersects]}


def _make_uncontained_pipeline(
    tile_w, tile_h, stride_x, stride_y, label_fields
):
    # Per sample, each field's list of label statuses (see _box_status_expr)
    project = {"_id": False}
    for i, (path, label_type) in enumerate(label_fields.items()):
        project["f%d" % i] = _label_statuses_expr(
            path, label_type, tile_w, tile_h, stride_x, stride_y
        )

    group = {"_id": None}
    for i in range(len(label_fields)):
        key = "f%d" % i
        group[key + "_count"] = {"$sum": {"$size": "$" + key}}
        group[key + "_uncontained"] = {
            "$sum": {
                "$size": {
                    "$filter": {
                        "input": "$" + key,
                        "cond": {"$gt": ["$$this", _FITS]},
                    }
                }
            }
        }
        group[key + "_too_large"] = {
            "$sum": {
                "$size": {
                    "$filter": {
                        "input": "$" + key,
                        "cond": {"$eq": ["$$this", _TOO_LARGE]},
                    }
                }
            }
        }

    return [{"$project": project}, {"$group": group}]


def _label_statuses_expr(path, label_type, tile_w, tile_h, stride_x, stride_y):
    field = "$" + path
    box_status = _box_status_expr(tile_w, tile_h, stride_x, stride_y)

    if issubclass(label_type, _LIST_TYPES):
        list_field = label_type._LABEL_LIST_FIELD
        single_type = fol._LABEL_LIST_TO_SINGLE_MAP[label_type]
        statuses = {
            "$map": {
                "input": {"$ifNull": [field + "." + list_field, []]},
                "as": "label",
                "in": _label_box_expr(
                    "$$label", single_type, box_status, None
                ),
            }
        }
    else:
        status = _label_box_expr(field, label_type, box_status, None)
        statuses = {
            "$cond": [
                {"$eq": [{"$type": field}, "object"]},
                [status],
                [],
            ]
        }

    # Labels without a box have no status
    return {"$filter": {"input": statuses, "cond": {"$ne": ["$$this", None]}}}


def _box_status_expr(tile_w, tile_h, stride_x, stride_y):
    """The status of the box ``$$x, $$y, $$w, $$h`` in the image's tiles:
    ``_FITS`` if a tile fully contains it, ``_TOO_LARGE`` if it is larger
    than a tile in at least one dimension, and ``_CROSSES`` otherwise.

    Tiles form a grid, so a tile contains the box if and only if a column of
    tiles contains its horizontal extent and a row of tiles contains its
    vertical extent.
    """
    return {
        "$max": [
            _span_status_expr(
                "$$x", "$$w", "$metadata.width", tile_w, stride_x
            ),
            _span_status_expr(
                "$$y", "$$h", "$metadata.height", tile_h, stride_y
            ),
        ]
    }


def _span_status_expr(start, size, img_len, tile_len, stride):
    """The status of the normalized span ``[start, start + size]`` in the
    tiles of one dimension; mirrors :meth:`compute_tiles`.

    The best candidate to contain the span is the last tile that starts at
    or before it.
    """
    # The span's part inside the image, in pixels
    a = {"$multiply": [_clamp_expr(start), img_len]}
    b = {"$multiply": [_clamp_expr({"$add": [start, size]}), img_len]}

    # Tiles are clamped to the image, and the last one ends at its edge
    width = {"$min": [tile_len, img_len]}
    last_start = {"$subtract": [img_len, "$$width"]}

    # Normalized coordinates carry float rounding, so edges are compared with
    # the same tolerance as when filtering labels, in pixels
    a_tol = {"$add": ["$$a", {"$multiply": [_EPS, img_len]}]}
    b_tol = {"$subtract": ["$$b", {"$multiply": [_EPS, img_len]}]}

    start_before = {
        "$cond": [
            {"$gte": [a_tol, "$$last"]},
            "$$last",
            {"$multiply": [{"$floor": {"$divide": [a_tol, stride]}}, stride]},
        ]
    }

    return {
        "$let": {
            "vars": {"a": a, "b": b, "width": width},
            "in": {
                "$let": {
                    "vars": {"last": last_start},
                    "in": {
                        "$cond": [
                            {
                                "$gt": [
                                    {"$subtract": [b_tol, "$$a"]},
                                    "$$width",
                                ]
                            },
                            _TOO_LARGE,
                            {
                                "$cond": [
                                    {
                                        "$gte": [
                                            {
                                                "$add": [
                                                    start_before,
                                                    "$$width",
                                                ]
                                            },
                                            b_tol,
                                        ]
                                    },
                                    _FITS,
                                    _CROSSES,
                                ]
                            },
                        ]
                    },
                }
            },
        }
    }


def _clamp_expr(value):
    """Clamps a normalized coordinate to the image."""
    return {"$min": [{"$max": [value, 0]}, 1]}
